# Cloud Database Connection Settings
spring.datasource.url=jdbc:mysql://portfolio-db-kevinlokesh333-86fe.h.aivencloud.com:15677/defaultdb?ssl-mode=REQUIRED&allowPublicKeyRetrieval=true
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate Production Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# Keep your server running on port 8080 inside Render's environment
server.port=8080